# Generated by Django 2.1.7 on 2019-04-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='user_check',
            field=models.CharField(default='B', max_length=1),
        ),
    ]
